#%RAML 1.0 DataType

type: object
properties:
  id:
    type: string
    example: "new001"
  author:
    type: string
    example:  "investors.com"
  title:
    type: string
    example:  "Futures: Chip Giant Says Growth 'Close'; LULU Soars On Earnings"
  description:
    type: string
    example: "Dow Jones futures rose solidly early Wednesday, along with S&P 500 futures and Nasdaq futures. Micron Technology (MU) and Lululemon Athletica (LULU) headlined earnings overnight. The stock market rally attempt had slim losses Tuesday, but the major indexes he…"
  url:
    type: string
    example:  "https://biztoc.com/x/754f091faaefd98c"
  urlToImage:
    type: string
    example:  "https://c.biztoc.com/p/754f091faaefd98c/og.webp"
  publishedAt:
    type: string
    example:  "2023-03-29T09:08:06Z"
  content: 
    type: string
    example: "Dow Jones futures rose solidly early Wednesday, along with S&amp;P 500 futures and Nasdaq futures. Micron Technology (MU) and Lululemon Athletica (LULU) headlined earnings overnight.The stock market … [+312 chars]"
